apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    {{- include "maybe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
    protocol: TCP
  selector:
    {{- include "maybe.labels" . | nindent 4 }}